### ISSUE TITLE
VOLK (libvolk) for vector computing

### ISSUE THREAD

**Issue by jj1bdx** [jj1bdx/airspy-fmradion#10]
Using [VOLK (libvolk)](http://libvolk.org/) makes the processing much faster, especially for the CPU-intensive functions such as the multipath filter. [The libvolk branch](https://github.com/jj1bdx/airspy-fmradion/tree/libvolk) is set for the migration.

Kudos to Takehiro Sekine for the suggestion!

**Comment by iroks** [comment]
you can also consider the usage of GPU; please take a look at this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5695887/

**Comment by jj1bdx** [comment]
@iroks I have no testing environment of GPU right now. I'm writing this software mostly by Mac mini 2018 with no external GPUs. BTW the paper looked informative. Thx!

**Comment by jj1bdx** [comment]
Ref: https://github.com/gnuradio/volk/pull/291

**Comment by jj1bdx** [comment]
VOLK seems stable both on macOS and Ubuntu, both on arm and x86_64. From v0.8.x libvolk is required.
