### ISSUE TITLE
Specifying duration to record + audio out question

### ISSUE THREAD

**Issue by jcdoster** [jj1bdx/airspy-fmradion#39]
I have two Airspys (or two RTL-SDRs) setup to record at progressive times, overlapping by a second. So, first SDR records 0 - 6 sec (to wav), second SDR 5 - 11 sec (to wav), first again 10 - 16 sec (to wav), second again 15 - 21 sec (to wav), so forth and so on. The reason, I want to check each interval for key phrases and words at a regular rep rate. The first and second SDRs are commanded from from separate threads, wav files are dumped into a common directory for examination. I've set this up on both an Ubuntu system and a Fedora system to cross check functionality. 

First question. With your very convenient program here -- love it -- how do I specify the duration of recording vice just commanding ^C to kill the program and stop the process. I didn't see anything in the help that states a clean way of stopping, vice just forcing it closed. 

Second question. I still don't have PortAudio working to go to a default audio device on the Fedora system, although it works just fine on the Ubuntu system. It's something to do with PortAudio interfacing with the MIMIX mini pc the Fedora instantiation is loaded onto I think. Now, the wav file functionality is all I really need for now, and that works on both Ubuntu and Fedora compilations of aispy-fmradion just fine. So, finally to the question. Is there another way of trying to specify an audio out (not to file) besides the "-P -" I could try on the Fedora system?

Thx!

**Comment by jj1bdx** [comment]
@jcdoster 

On duration of recording: I use Linux command called *timeout*. An example:

```sh
timeout --foreground -k 10 170m airspy-fmradion -m fm -E100 -t airspyhf -q -c freq=89700000,srate=384000 -b 0.1 -G recording.wav -T recording.pps.txt
```

About PortAudio on Fedora: I guess PortAudio is based on ALSA. I don't know anything in detail about Fedora's audio system, but if you can look up the PortAudio device number, you can specify it after the `-P` option such as `-P 0`.
